### ISSUE TITLE
Python: ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by tarun018** [stanle/madopt#17] opened 2017-07-04 19:39 UTC
Hey! 

I am using python multiprocessing to run 5 instances of different bonmin models in parallel. However this is giving me following error:

> Traceback (most recent call last):
  File "State.py", line 1111, in <module>
    class Driver:
  File "State.py", line 1114, in Driver
    a.EM()
  File "State.py", line 748, in EM
    rss = pr.get(timeout=5)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: signal only works in main thread

However optimization using ampl objects is perfectly fine. Is Madopt supposed to have some issues with multiprocessing ?

Please help!

**Comment by stanle** [comment] 2017-07-05 07:31
Thank you for reporting this.

I can confirm the bug and I have committed a potential fix to the master branch. 

please test the latest version.

**Comment by tarun018** [comment] 2017-07-05 20:33
Thanks for the quick response. However I installed madopt earlier using pip and now while building python using:

`python setup.py install`

I am getting linking error:

> running install
running build
running build_py
running build_ext
skipping 'src/madopt.cpp' Cython extension (up-to-date)
building 'madopt' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/madopt.cpp -o build/temp.linux-x86_64-2.7/src/madopt.o --std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/madopt.cpp:1321:15: warning: ‘double __pyx_f_6madopt_callback_template(void*, void*)’ defined but not used [-Wunused-function]
 static double __pyx_f_6madopt_callback_template(void *__pyx_v_parameter, void *__pyx_v_method) {
               ^
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/madopt.o build/libmadopt.a build/libmadopt_ipopt.a build/libmadopt_bonmin.a -lipopt -lbonmin -o build/lib.linux-x86_64-2.7/madopt.so
/usr/bin/ld: cannot find -lipopt
/usr/bin/ld: cannot find -lbonmin
collect2: error: ld returned 1 exit status

I have bonmin/build/lib in my LIBRARY_PATH as well as LD_LIBRARY_PATH.

**Comment by stanle** [comment] 2017-07-06 18:19
Have you tried setting the path in cmake
```
cmake -DCUSTOM_LIBRARY=/path/to/bonmin/libs -DCUSTOM_INCLUDE=/path/to/bonmin/includes
```

**Comment by tarun018** [comment] 2017-07-06 18:21
Yes I have used the following command:

`cmake -DCUSTOM_LIBRARY=/path/to/bonmin/lib -DCUSTOM_INCLUDE=/path/to/bonmin/include ..`

Still getting the same linking error. I also verified that my /path/to/bonmin/lib has libbonmin.so and libipopt.so.

**Comment by tarun018** [comment] 2017-07-08 10:27
Is there any solution to the issue ? Could you provide me with an updated release ?

**Comment by tarun018** [comment] 2017-07-08 11:07
Thank you ! The issue has been resolved.

**Comment by tarun018** [comment] 2017-07-09 17:46
The issue seems to be reappearing again.

**Comment by stanle** [comment] 2017-07-13 16:41
Sorry to hear that. But I do not know how I can help you. This seems to be an error related to your computer setup.

**Closed as completed** 2017-08-22 19:16 UTC
Labels: bug
