### ISSUE TITLE
Segfault in C++ example

### ISSUE THREAD

**Issue by domluna** [stanle/madopt#15] opened 2017-04-07 01:27 UTC
```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.1, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:     2994
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:     1997

Total number of variables............................:     1000
                     variables with only lower bounds:        0
                variables with lower and upper bounds:     1000
                     variables with only upper bounds:        0
Total number of equality constraints.................:      998
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

Segmentation fault: 11
```

the segfault is happening when calling `m.solve()`. Tried also with Ipopt 3.12.7 and get the same result.

**Comment by domluna** [comment] 2017-04-07 05:05
Nvm, just need to set the limited-memory option.

**Comment by domluna** [comment] 2017-04-07 21:17
Reopening since it seems if `m.setStringOption("hessian_approximation", "limited-memory");` isn't set it crashes and I'm guessing this isn't the intended behaviour.

```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.5, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:       15
Number of nonzeros in inequality constraint Jacobian.:        2
Number of nonzeros in Lagrangian Hessian.............:       11

Total number of variables............................:        8
 variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        6
Total number of inequality constraints...............:        2
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        2
        inequality constraints with only upper bounds:        0

fish: './mpc' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by paul-scott** [comment] 2017-06-19 00:48
This issue might have been fixed in the above pull request.

**Comment by stanle** [comment] 2017-07-05 15:29
I cannot reproduce this issue. If fixing #16 did not solve it, please re-open.

**Closed as completed by stanle** 2017-07-05 15:29 UTC
